version: '3'

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: northwind_dw
      POSTGRES_USER: northwind_user
      POSTGRES_PASSWORD: thewindisblowing
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./data/northwind-dw.sql:/docker-entrypoint-initdb.d/northwind-dw.sql
    ports:
      - 5433:5432